### PR TITLE
add git-diff function

### PR DESCRIPTION
**Pull request by legalsylvain**
CC @rvalyi / @sebastienbeau / @hparfr .

### CODE REVIEW

**Comment by rvalyi** [comment]
the feature looks nice!

**Comment by bealdav** [comment]
I prefer AkDiff and only git implemented for now

**Comment by sebastienbeau** [comment]
Agree with David it's better to name the command  ak diff (it's shorter). But weonly implement git as bzr is dead

**Comment by sebastienbeau** [comment]
@legalsylvain good job ;)

**Comment by legalsylvain** [comment]
You're all on github on Sunday ? ;-)

Done. https://github.com/akretion/ak/pull/4

**Pull request merged**
