### PR TITLE
Add ak sparse

### PR DESCRIPTION
**Pull request by hparfr**
Integrate `git sparse-checkout` in ak.
Needs  recent git version.

Usage:

```yml
# spec.yaml
server-tools:
    modules:
        - module_auto_update
        - sentry
        - base_exception
        - base_jsonify
        - onchange_helper
        - base_view_inheritance_extension
    src: https://github.com/OCA/server-tools 12.0
```

```sh
$ ak sparse
```
There wil be only the 6  directories in server-tools folder.

`ak sparse -d server-tools` for specific directory.

`ak sparse --disable` to reset and have all directories back.

### CODE REVIEW

**Comment by bealdav** [comment]
What is the goal ? Disk usage ?

**Comment by hparfr** [comment]
1) In prod, reduce the size of docker image and speed up the construction by sending in the context only relevent modules.
2) In dev, reduce the load for IDE, improve visiblity, reduce errors of editing the good file in the wrong folder  by removing unused folders
3) In future, will be used with promising git new feature: partial clones. It will allows us to download only the necessary files from remotes.

**Comment by bealdav** [comment]
>     2. In dev, reduce the load for IDE, improve visiblity, reduce errors of editing the good file in the wrong folder  by removing unused folders

Definitively yes

**Comment by bealdav** [comment]
git can be update in all OS I assume.

Then it could replace ak build ? or we could merge feature ak build ?

**Comment by hparfr** [comment]
``` 
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git -y
```

>Then it could replace ak build ? or we could merge feature ak build ?
You mean links in `ak build`, I think it's still relevant to have a simple and constant path.
And doing simply a 'ls -l' in links tells you if there is something wrong (broken path).

**Comment by bealdav** [comment]
In workflow you run:

ak build && ak sparse ??

**Comment by hparfr** [comment]
Not every time.

When I adds modules, I do `ak sparse ` as often as I do ` ak build --links`

**Comment by hparfr** [comment]
I think it's too early to integrate deeply ak build and ak sparse.
I want more feedback from all of you guys, and it requires a too recent version of git.

**Comment by rvalyi** [comment]
stupid question before I can judge how useful it is: how do you guys populate modules in
```
# spec.yaml
server-tools:
    modules:
        - module_auto_update
        - sentry
        - base_exception
        - base_jsonify
```
and how do you update that list? Manually with selects?

**Comment by hparfr** [comment]
Yes. Btw, it's not something new. We already do that to use the links
feature.


Le sam. 16 mai 2020 à 05:40, Raphaël Valyi <notifications@github.com> a
écrit :

**Pull request merged**
