### PR TITLE
fixes default db ownership https://github.com/akretion/voodoo/issues/50

### PR DESCRIPTION
**Pull request by rvalyi**
Note: I put a try/catch because eventually voodoo is used with a remote database or production configuration and the check/ownership fix may fail.

### CODE REVIEW

**Comment by hparfr** [comment]
It seams dangerous.
Why not change the user in the .cfg of the project ?

**Comment by rvalyi** [comment]
@hparfr why dangerous?

We cannot use configuration because the default database called db is created by the Postgres container itself at startup with the postgres owner and it cannot be changed before creation. Now to have a simple Odoo configuration and simple psql  commands, we need the databased to be own by odoo, the unix user of the Odoo process. Soo what do you think?

**Comment by sebastienbeau** [comment]
I think we should fixe the postgresql container that create the database, we should directly create it with the right user instead of hacking it later

**Comment by rvalyi** [comment]
@sebastienbeau we could do that only if we fork the Postgres official image, I'm really not sure it is any simpler...

**Comment by sebastienbeau** [comment]
We already use a custom image https://github.com/akretion/voodoo-postgresql

**Comment by sebastienbeau** [comment]
This have been fixed here: https://github.com/akretion/docker-postgresql/commit/4626a1f78074700026c909f7cc0a018875b7e2eb

**Pull request closed without merging**
